version: '3.2'
services: 
  parrotapi:
    build: ParrotApi
    ports:
      - '5000:5000'
    networks:
      - custom-network
  parrotdetailsapi:
    build: ParrotDetailsApi
    ports:
      - '5001:5001'
    networks:
      - custom-network
  parrotweb:
    build: BlueParroWeb
    ports:
      - '5002:5002'
    networks:
      - custom-network

networks:
  custom-network:
    external:
      name: parrot-net
  