version: '3.2'

services: 
  jenkins-master:
    build: docker-jenkins/jmaster
    ports:
      - '8080:8080'
    volumes:
      - "$HOME/jenkins_home:/var/jenkins_home"
    container_name: jenkins-master
    networks:
      - custom-network

networks:
  custom-network:
    external:
      name: parrot-net
